services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: db01
      POSTGRES_USER: victor
      POSTGRES_PASSWORD: 12345@Victor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U victor -d db01"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  django-web:
    build: .
    container_name: django-tornac
    ports:
      - "127.0.0.1:8001:8001"
    volumes:
      - .:/app 
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

volumes:
  postgres_data:
  