# Generated by Django 5.2.8 on 2025-11-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Aplicativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('titulo', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('cm', 'Concluído'), ('ds', 'Em Desenvolvimento')], default='ds', max_length=2)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(max_length=150)),
                ('tags', models.ManyToManyField(related_name='taged', to='pages.tag')),
            ],
        ),
    ]
