# Generated by Django 5.2.8 on 2025-11-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicativo',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='taged', to='pages.tag'),
        ),
    ]
