# Generated by Django 5.2.8 on 2025-11-24 22:44

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_aplicativo_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicativo',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, help_text='Imagem do projeto (400x200px recomendado)', null=True, upload_to='projetos/', variations={'card': {'crop': True, 'height': 200, 'width': 400}, 'thumbnail': {'crop': True, 'height': 100, 'width': 100}}),
        ),
        migrations.AddField(
            model_name='aplicativo',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
