# Generated by Django 5.2.8 on 2025-11-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_aplicativo_imagem_aplicativo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicativo',
            name='repositorio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='nome',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
